---
apiVersion: v1
kind: Service
metadata:
  name: vsx-bulwark
  labels:
    app: vsx-bulwark
spec:
  selector:
    app: vsx-bulwark
  ports:
    - name: http
      port: 18003
      targetPort: http
      protocol: TCP
  type: ClusterIP
