---
apiVersion: v1
kind: Service
metadata:
  name: pypi-bulwark
  labels:
    app: pypi-bulwark
spec:
  selector:
    app: pypi-bulwark
  ports:
    - name: http
      port: 18000
      targetPort: http
      protocol: TCP
  type: ClusterIP
