version: '3.9'

services:
  bulwark-npm:
    build:
      context: .
      dockerfile: npm-bulwark/Dockerfile
    ports:
      - "18001:18001"
    volumes:
      - ./npm-bulwark/config-best-practices.yaml:/config.yaml:ro
    networks:
      - bulwark-demo

  bulwark-pypi:
    build:
      context: .
      dockerfile: pypi-bulwark/Dockerfile
    ports:
      - "18000:18000"
    volumes:
      - ./pypi-bulwark/config-best-practices.yaml:/config.yaml:ro
    networks:
      - bulwark-demo

  bulwark-maven:
    build:
      context: .
      dockerfile: maven-bulwark/Dockerfile
    ports:
      - "18002:18002"
    volumes:
      - ./maven-bulwark/config-best-practices.yaml:/config.yaml:ro
    networks:
      - bulwark-demo

networks:
  bulwark-demo:
    driver: bridge
