---
apiVersion: v1
kind: Service
metadata:
  name: maven-bulwark
  labels:
    app: maven-bulwark
spec:
  selector:
    app: maven-bulwark
  ports:
    - name: http
      port: 18002
      targetPort: http
      protocol: TCP
  type: ClusterIP
