---
apiVersion: v1
kind: Service
metadata:
  name: npm-bulwark
  labels:
    app: npm-bulwark
spec:
  selector:
    app: npm-bulwark
  ports:
    - name: http
      port: 18001
      targetPort: http
      protocol: TCP
  type: ClusterIP
